development:
  adapter: postgresql
  database: memocity_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: memocity_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: memocity_prod
  pool: 5
  timeout: 5000
